### PR TITLE
Updating prod .travis.yml to "new process"

### PR DESCRIPTION
**Pull request by dmajones**
Hey Aksel, 
can you review the changes to .travis.yml in prod before I merge the changes? Thanks

### CODE REVIEW

**Review by akseldavis — CHANGES_REQUESTED** [review]
I'd recommend using the same branch and commit from ontap-internal. Once you've pushed to ontap-internal, push the same commit to ontap-prod using `git push public <branchname>`. You will still have to create and merge pull requests in each repository, but this way you only make the changes one time. That way the two repositories will stay in-synch.

**Comment by akseldavis** [comment]
If your -internal changes are on a different branch, you may want to close (not merge) this pull request, push your -internal changes to prod, open a new pull request on prod, and then merge it.

**Comment by dmajones** [comment]
Question - the "if" statement in prod is different than the "if" statement in internal....so would you still recommend doing it this way even though the "if" statements need to be reflected differently for each repo (prod vs internal)?

**Comment by akseldavis** [comment]
They should be the same. That's why I'm suggesting not to change line 6. To your point, if we were okay with the two repositories being different, I'd suggest the internal .travis.yml be `if: repo =~ /-internal/` and production be `if: branch = master`. We can include both conditionals as it was before so that the file can be consistent across both repositories.

**Pull request merged**
