### PR TITLE
Update install-mediator-pkg-task.adoc

### PR DESCRIPTION
**Pull request by dkambleNetapp**
Field Support had a feedback about the User-Guide:

"Given that the UEFI setting can be a showstopper for installation, I recommend putting the information about UEFI within the steps itself in the docs page.

When the information is in the steps section, it illustrates that the information provided is needed in some fashion for a successful installation. Currently it is in the "About this task" section, which does not properly illustrate the full importance of the UEFI secure boot setting notice."

Hence, making a change to move the "About this task" content as Step 2.

### CODE REVIEW

**Comment by netapp-ehoffman** [comment]
@netapp-thomi , please review the changes; once you're good with the modifications, you'll need to pass this issue to Amanda for implementation

**Review by netapp-thomi — APPROVED** [review]

**Comment by netapp-thomi** [comment]
Thank you Dhananjay for making this suggestion.   We will make the changes in the next few days.

**Comment by netapp-thomi** [comment]
Hi Amanda,  This change is ready to merge with public repo.

**Comment by netapp-aherbin** [comment]
The changes have been implemented and are live.

**Pull request closed without merging**
