### PR TITLE
Add Amazon FSx for NetApp ONTAP for SnapMirror

### PR DESCRIPTION
**Pull request by Yoshiki0705**
Mention for Amazon FSx for NetApp ONTAP for SnapMirror interoperability of Unified replication.

### CODE REVIEW

**Comment by Yoshiki0705** [comment]
I understand as CVO version and Amazon FSx for NetApp ONTAP version sync, and mentioned as this style. You can suggest and add words to make it clear this point before approving or rejecting it.

**Comment by netapp-ahibbard** [comment]
@Yoshiki0705 thanks for your PR. We are reviewing and will address as soon as possible

**Comment by Yoshiki0705** [comment]
> @Yoshiki0705 thanks for your PR. We are reviewing and will address as soon as possible

@netapp-ahibbard thank for checking it. Do you have any idea or updates for this?

**Comment by netapp-ahibbard** [comment]
@Yoshiki0705 . Thanks for raising this. Please contact Amazon using the Feedback function of the doc site to request updates to [FSx documentation](https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html).

**Comment by Yoshiki0705** [comment]
@netapp-ahibbard 
Thank for your comment. I have already done this for AWS side.
Now, we are asked from AWS to update NetApp documentation, because they cannot mention NetApp ONTAP matrix by their hands. Once we update our matrix mention Amazon FSx for NetApp ONTAP, they can update their site to link our matrix.

**Pull request closed without merging**
